debug: true
mysql:
  host: localhost
  schema: spaceraiders
  user: root
  password: password


default-parts:
  small:
    hull: scout
    engine: scout
  medium:
    hull: none
    engine: none
  large:
    hull: none
    engine: none