package net.novapixelnetwork.spaceraiders.entity

import net.novapixelnetwork.spaceraiders.data.DataManager
import org.bukkit.Location
import java.util.*

/**
 * Created by owner on 1/5/2018.
 */
class Hangar(val id: Int, val center: Location, val size: Size, val owner: UUID, private val shipID: Int, val autoGenerated: Boolean, val planet: Int?) {

    val ship: Ship by lazy {
        DataManager.getShip(shipID)
    }

    enum class Size(val sizeName: String) {
        SMALL("Scout"), MEDIUM("Fighter"), LARGE("Destroyer");

        override fun toString(): String {
            return sizeName
        }

    }
}