package net.novapixelnetwork.spaceraiders.ship

import net.novapixelnetwork.spaceraiders.data.DataManager
import net.novapixelnetwork.spaceraiders.world.Planet
import org.bukkit.Location
import java.util.*

/**
 * Created by owner on 1/5/2018.
 */
class Hangar(val id: Int, val center: Location, val size: Size, val owner: UUID, private val shipID: Int, val autoGenerated: Boolean, val planet: Planet) {

    val ship: Ship by lazy {
        DataManager.getShip(shipID)!!
    }

    companion object {
        fun createTable(): String{
            return "CREATE TABLE IF NOT EXISTS hangars (" +
                    "id INT AUTO_INCREMENT, " +
                    "x INT NOT NULL, " +
                    "y INT NOT NULL, " +
                    "z INT NOT NULL, " +
                    "planet INT, " +
                    "size VARCHAR(12) NOT NULL, " +
                    "ship INT NOT NULL, " +
                    "auto_generated TINYINT(1) NOT NULL, " +
                    "owner VARCHAR(36) NOT NULL, " +
                    "PRIMARY KEY (`id`));"
        }
    }

    enum class Size(val sizeName: String) {
        SMALL("Scout"), MEDIUM("Fighter"), LARGE("Destroyer");

        override fun toString(): String {
            return sizeName
        }
    }
}